steps:
  - id: 'Install Dependencies'
    name: 'python'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  - id: 'Run Tests'
    name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pip install -r requirements.txt && pip uninstall -y importlib-metadata && pytest app/tests'




  - id: 'Dockerize'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/python-app:latest', '.']

  - id: 'Push to GCR'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/python-app:latest']

  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'python-app'
      - '--image=gcr.io/$PROJECT_ID/python-app:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
